config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: ''

  resources :inbound_messages, only: :create

  resources :subscriptions, except: [:index, :destroy]

  match '/about', :to => 'home#about', :via => [:get]

  root to: "home#index"
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  belongs_to :user, inverse_of: :contact
  validates_presence_of :user

  validates :phone_number, length: {is: 12, message: "does not appear to be valid"}
  before_validation NormalizePhoneNumber.new :phone_number

  def notified?
    notified_at.present?
  end

end

app/models/inbound_message.rb
class InboundMessage < ActiveRecord::Base
  validates_presence_of :from, :to

  belongs_to :user

  after_initialize NormalizePhoneNumber.new :from

  scope :most_recent, -> {joins('LEFT OUTER JOIN inbound_messages im ON im.user_id = inbound_messages.user_id AND inbound_messages.id < im.id').where('im.id is null')}
end

app/models/s_m_s.rb
class SMS < ActiveRecord::Base
  include Phone

  before_create :set_user
  belongs_to :user

  private
  def set_user
    self.user_id = User.find_by(phone_number: from).try(:id)
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user

  scope :active, -> {where(active: true)}

  def deactivate!
    update active: false
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :subscription, dependent: :nullify
  has_many :inbound_messages

  before_validation NormalizePhoneNumber.new :phone_number
  validates :phone_number, length: {is: 12, message: "does not appear to be valid"}

  has_one :contact, inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :contact

  delegate :phone_number, :notified?, to: :contact, prefix: true, allow_nil: true

  scope :active, -> {joins(:subscription).merge(Subscription.active)}

  HOURS_TO_RESPOND = 24

  def identity
    name || email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone_number << {contact_attributes: [:phone_number]}
    devise_parameter_sanitizer.for(:edit) {|u| u.permit(:name, :email, :phone_number, :password, :password_confirmation, :time_zone, :contact_attributes => [:name, :phone_number])}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end
end

app/controllers/inbound_messages_controller.rb
class InboundMessagesController < ApplicationController
  skip_before_filter  :verify_authenticity_token, only: [:create]
  include Plivo

  def create
    message = InboundMessage.new inbound_message_params
    LinkMessageToUser.new(message).call
    render xml: "<Response/>", status: message.save ? 201 : 400
  end

  private

  def inbound_message_params
    params.deep_transform_keys!(&:underscore).permit(:from, :to, :text, :message_uuid)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def create
    CreateStripeCustomer.perform_async(current_user.id, 'token')
  end

  def edit
    
  end

  def update
  end

  def show
  end

  def cancel
    subscription.deactivate!
    CancelSubscription(subscription.stripe_customer_token)
  end

  private
  def subscription
    @subscription ||= current_user.subscription
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include FormattedErrors

  def new
    @user = User.new
    @user.build_contact
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to_path user_path(@user)
    else
      render status: 400, json: format_error_messages(@user)
    end
  end

  def update
  end

  def show
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :password, :password_confirmation, :time_zone, :contact_attributes => [:name, :phone_number])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/inbound_messages_helper.rb
module InboundMessagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.haml
%nav.top-bar{data: {topbar: ''}}
  %ul.title-area
    %li.name
      %h1
        %a{href: '/'} ShoutTrout
  %section.top-bar-section
    %ul.right
      %li
        %a{href: '/about'} About
      %li
        %a{href: '/sign_in'} Log In

app/views/home/about.html.haml
%p buk!

app/views/home/index.html.haml
= render partial: 'header'

.row.large-12.full-width
  = link_to image_tag("http://placehold.it/2560x600/37646F/fff&text=ShoutTrout!")

.row.full-width.hero{style: "background-color: #37646F; color: #FFF"}
  .large-4.columns
    %h3
      %i.fi-comment
      Your Daily Message
    %p Once a day, one of our trouts will send a text message to your phone
  .large-4.columns
    %h3
      %i.fi-mobile
      Check In With Us
    %p Some time in the next 24 hours, just send a reply to let us know you got it
  .large-4.columns
    %h3
      %i.fi-megaphone
      We've Got Your Back
    %p If we don't hear from you, we will let your contact know that something's fishy!

.row.large-6
  .large-4.columns
    %h3
      %i.fi-arrow-up
      Sign up
    = form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
      = devise_error_messages!
      = f.telephone_field :phone_number, placeholder: 'Phone Number'
      = f.text_field :email, placeholder: 'Email address'
      = f.password_field :password, placeholder: 'Password'
      = f.submit "Let's do this!", class: "button radius"
  .large-4.columns
    %h3
      %i.fi-key
      Sign in
    = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
      = f.text_field :email, placeholder: 'Email address'
      = f.password_field :password, placeholder: 'Password'
      - if devise_mapping.rememberable?
        = f.check_box :remember_me
        = f.label :remember_me, style: "height: 2.3125rem; margin-bottom: 1rem; padding: 0.5rem;"
      %br
      = f.submit "Sign in", class: "button radius"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "ShoutTrout" %></title>

    <%= yield(:head) if content_for?(:head) %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= yield :javascripts %>
    <%= javascript_include_tag "application" %>
    
  </body>
</html>

app/views/subscriptions/create.html.haml
%h1 Subscriptions#create
%p Find me in app/views/subscriptions/create.html.haml

app/views/subscriptions/edit.html.haml
%h1 Subscriptions#edit
%p Find me in app/views/subscriptions/edit.html.haml

app/views/subscriptions/new.html.haml
- content_for :head do
  = tag :meta, name: 'stripe-key', content: STRIPE_PUBLIC_KEY

= render partial: 'home/header'

- content_for :javascripts do
  = javascript_include_tag "stripe.v2.min.js"

app/views/subscriptions/show.html.haml
%h1 Subscriptions#show
%p Find me in app/views/subscriptions/show.html.haml

app/views/subscriptions/update.html.haml
%h1 Subscriptions#update
%p Find me in app/views/subscriptions/update.html.haml

app/views/users/destroy.html.haml
%h1 Users#destroy
%p Find me in app/views/users/destroy.html.haml

app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.haml

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml

.large-4.columns
  = form_for @user, remote: true do |f|
    = f.label :name
    = f.text_field :name
    = f.label :phone_number
    = f.text_field :phone_number
    = f.label :email
    = f.text_field :email
    = f.label :password
    = f.password_field :password
    = f.label :password_confirmation
    = f.password_field :password_confirmation
    = f.label :hour_to_send_message, "When would you like your daily message? (PST)"
    = f.select :hour_to_send_message, options_for_select( (1..11).map {|hr| ["#{hr} AM", hr]} + [['Noon', 12]] + (1..11).map {|hr| ["#{hr} PM", hr + 12]} + [['Midnight', 0]], 12)
    = f.fields_for :contact do |c|
      = c.label :contact_name
      = c.text_field :name
      = c.label :contact_phone_number
      = c.text_field :phone_number
    = f.submit

app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.haml

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml